# Generated by Django 3.2 on 2021-04-22 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('Isbn', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
